### ISSUE TITLE
s/Ini/INI/ 

### ISSUE THREAD

**Issue by codemartial** [pierrec/go-ini#1]
According to Go conventions of [initialism](https://github.com/golang/go/wiki/CodeReviewComments#initialisms):

> Words in names that are initialisms or acronyms (e.g. "URL" or "NATO") have a consistent case. For example, "URL" should appear as "URL" or "url" (as in "urlPony", or "URLPony"), never as "Url"

So the struct `Ini `should ideally be `ini` or `INI`. Since it's an exported struct the latter is the only option. I got the code changes successfully built and tested by doing the following:

`gofmt -s -w -r 'Ini -> INI' -d *.go`

Since the struct `Ini` doesn't actually appear in user code (as illustrated in the examples), renaming it shouldn't require anything more than a recompilation of the user code.

**Comment by pierrec** [comment]
Oh indeed you are right.

Thank you.
